### ISSUE TITLE
SQL IN operator

### ISSUE THREAD

**Issue by milantrax** [neerajsinghsonu/PDO_Class_Wrapper#7]
Is it possible something like this, with IN operator:
SELECT * FROM Customers WHERE City IN ('Paris','London');
Thanks

**Comment by neerajsinghsonu** [comment]
Hi Milantrax,

Yes, you can use IN like below sample code with pdoQuery:

~~~php

/**
 *  Query with IN operator 
 */
$q = $db->pdoQuery('SELECT * FROM Customers WHERE City IN (?, ?);',array('Paris','London'))->showQuery()->results();
// print array result
$helper->PA($q); 
~~~

Sorry for any mistake's actually I am out for my weekend, so its just quick reply by my cell phone.

Cheers!!!
