### ISSUE TITLE
Do you have the latest version for PHP7 ?

### ISSUE THREAD

**Issue by hriziya** [neerajsinghsonu/PDO_Class_Wrapper#9]
Hi, I found your wrapper class helpful and so wanted to use it. but before I start using it, Is there any latest version of the wrapper class available with you ? 

I also read that new version coming soon in the introduction page but looks like this repo is not updated since last few years.. 

let me know if I can wait few days for latest version ?

Thanks

**Comment by neerajsinghsonu** [comment]
Hi @hriziya,

Thanks for your comment. Actually new and updated version is on the go, but can't release without proper test. I am not planning to update repo yet but yes in future you will find new and more optimize PDOClassWrapper with some new options and more easy way... I can't tell you the date, my time gonna stuck in my projects. Although , we will release the advance version as soon as possible for all... till then enjoy! cheers!! :) please also let us know your valuable feedback and suggestions if you have any 🔢
